version: '3.3'

services:
  db:
    build: ./mysql/
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "8000:3306"
    networks:
      - dockercompose
  
  backend:
    depends_on:
      - db
    build: ./flask/
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - "C:\\Users\\Matheus\\Documents\\GitHub\\Docker\\5-Compose\\6-Bind-Mount\\flask:/app"
    networks:
      - dockercompose

networks:
  dockercompose: